version: '3'

services:
  ota:
    build:
      context: .
      dockerfile: Dockerfile
    image: ota
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - DB_HOSTNAME=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DB_NAME=${PG_DB_NAME}
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - app-network

  ota_db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    ports:
      - "5432:5432"
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:  