version: '3'

services:
  ota:
    build:
      context: .
      dockerfile: Dockerfile
    image: ota
    env_file: .env
    environment:
      - DB_USERNAME=$PG_USER
      - DB_PASSWORD=$PG_PASSWORD
      - DB_HOSTNAME=ota_db
      - DB_PORT=$PG_PORT
      - DB_NAME=$PG_DB_NAME
    ports:
      - "3333:33333"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - app-network

  ota_db:
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_USERNAME=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASSWORD
      - POSTGRES_DATABASE=$PG_DB_NAME
    ports:
      - "5432:5432"
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:  